### PR TITLE
Uinput ff upload erase support

### PR DESCRIPTION
**Pull request by ndreys**
As mentioned in the title, this is a bunch of changes I had to make in order to use the library for uinput FF-effect testing. FF-event injecting part was tested on both uinput and a real game controller device. 

In case this is useful, here are Jupyter notebooks I used to test examples I added to documentation: [uinput-ff-jupyter-notebooks.zip](https://github.com/gvalkov/python-evdev/files/2276121/uinput-ff-jupyter-notebooks.zip)

### CODE REVIEW

**Comment by gvalkov** [comment]
Truly awesome work @ndreys :+1: Thank you for contributing!

**Comment by drewcovi** [comment]
@gvalkov @ndreys  for context, I'm building this using resin.io to deploy to raspberry pis

not sure if there's an undocumented dependency or if it just needs to be declared.

**Comment by ndreys** [comment]
@drewcovi This constant comes from Linux kernel headers and it isn't really a new dependency. The constant was introduced around 4.3-rc4 time-frame, what kernel version is your system building against?

**Comment by drewcovi** [comment]
@ndreys I’m building for ResinOS which is effectively Raspbian, which is apparently using a 4.14 Linux kernel I believe.

Seems this is used a lot in SBC devices, but perhaps I missed something.

**Comment by ndreys** [comment]
@drewcovi, sorry no idea then. I've never used ResinOS and have no idea how it works, so debugging its build process is not something I can do.

**Comment by gvalkov** [comment]
Just FIY - this was fixed a few days ago. See #98.

**Pull request merged**
