### PR TITLE
threaded_close

### PR DESCRIPTION
**Pull request by sezanzeb**

### CODE REVIEW

**Comment by sezanzeb** [comment]
I'd say we revert the change now

**Comment by sezanzeb** [comment]
@gvalkov bump

**Comment by sezanzeb** [comment]
@gvalkov do you still intend to maintain this?

If not, there hardly are any pull requests or problems so I don't mind maintaining it. I'm experienced with python-evdev and maintaining github projects due to my work on https://github.com/sezanzeb/input-remapper/

**Comment by sezanzeb** [comment]
@gvalkov please add me as a maintainer

**Comment by gvalkov** [comment]
Hello @sezanzeb. Thanks for offering to help. I've added you as a maintainer/collaborator.

**Comment by gvalkov** [comment]
Thanks.

**Comment by sezanzeb** [comment]
> Hello @sezanzeb. Thanks for offering to help. I've added you as a maintainer/collaborator.

Thanks a lot! :)

**Pull request merged**
