### PR TITLE
Added docs about `asyncio` support

### PR DESCRIPTION
**Pull request by paulo-raca**
And I'm finally done! (I hope...)

python-evdev now does everything I want from it :D

Thanks for the awesome library, and the code reviews

### CODE REVIEW

**Comment by gvalkov** [comment]
Merged in 60b590a66d7e4e1a9b141d4b8c855bfffa7087da

**Comment by gvalkov** [comment]
The new `asyncio` functionality is awesome. I'm really glad you scratched your own personal itch with python-evdev and in the process made it better for everyone.

**Comment by gvalkov** [comment]
There are more than enough changes for a new release at this point, but I think I'll wait at least a few days in case something pops up.

**Comment by paulo-raca** [comment]
Waiting a few days is always a good idea ;)

**Pull request closed without merging**
